### ISSUE TITLE
type erro occur, when test case is failed

### ISSUE THREAD

**Issue by ansonGitHub** [ravikiranb36/htmltestrunner-rv.github.io#1]
HTMLTestRunner-rv version: 1.0.12 
Python version: 3.8.3
Operating System: Mac 10.14

when test case failed and generated report ,it failed at line 401 for runner.py
Actually  t's type class, but show erro type

![image](https://user-images.githubusercontent.com/12421184/113961236-51b08900-9858-11eb-96e9-937889647478.png)

**Comment by ravikiranb36** [comment]
can you post complete log

**Comment by ravikiranb36** [comment]
> HTMLTestRunner-rv version: 1.0.12
> Python version: 3.8.3
> Operating System: Mac 10.14
> 
> when test case failed and generated report ,it failed at line 401 for runner.py
> Actually t's type class, but show erro type
> 
> ![image](https://user-images.githubusercontent.com/12421184/113961236-51b08900-9858-11eb-96e9-937889647478.png)

can you post complete log
