### ISSUE TITLE
Does not work with unittesting.subTest

### ISSUE THREAD

**Issue by renzil** [ravikiranb36/htmltestrunner-rv.github.io#3]
The HTMLTestRunner does not display the test case at all in the output if the testcase has a subTest and any one fails.

The HTMLTestRunner displays the test case but the logs are blank if the testcase has a subTest and all succeed.

[What are subTests?](https://docs.python.org/3/library/unittest.html#distinguishing-test-iterations-using-subtests)

**Comment by ravikiranb36** [comment]
@renzil Can you provide screenshots

**Comment by jalapenopuzzle** [comment]
I confirm that running tests with failing subTest produces no output.
Please see screenshot below.

![HTMLTestReport_empty](https://github.com/ravikiranb36/htmltestrunner-rv.github.io/assets/8386278/dfd51615-40c2-4215-807e-eb4fc56b24fc)

**Comment by ravikiranb36** [comment]
Thanks for your input.
I will check

**Comment by ravikiranb36** [comment]
@jalapenopuzzle @renzil 
Issue resolved

Now it work for sub test also.
Thanks for your input
