### ISSUE TITLE
Passing absolute path to output fails

### ISSUE THREAD

**Issue by jalapenopuzzle** [ravikiranb36/htmltestrunner-rv.github.io#5]
Regarding the "output" argument:

1. Path processing does not play nice with Windows paths.
2. Path processing assumes path is relative to current working directory. Passing an absolute path fails.

Path processing should use the python 3 pathlib library to become OS independent.
<https://docs.python.org/3/library/pathlib.html>

Passing an absolute path on windows causes issues rooted at the following lines:

HTMLTestRunner/runner.py:319
```
        self.html_report_file_name = f'./{self.output}/{self.report_name}_{time.strftime("%d-%m-%y %I-%M-%S")}.html'
        os.makedirs(os.path.dirname(self.html_report_file_name), exist_ok=True)
        self.log_file = ''
        if log:
            self.log_file = f'./{self.output}/{self.report_name}_{time.strftime("%d-%m-%y %I-%M-%S")}_log.txt'
```

**Comment by ravikiranb36** [comment]
Okay. I will check

**Comment by ravikiranb36** [comment]
@jalapenopuzzle 
Thanks for notify the issue. 
Issue resolved
